//AUTOGENERATED FILE: DO NOT EDIT
#ifndef kaynesgameoflife_HPP_
#define kaynesgameoflife_HPP_
#include <MINX/Game.hpp>
#include <MINX/GameTime.hpp>

using namespace MINX;

namespace KayneGameOfLife
{
	class GameOfLife : public Game
	{
		public:
			GameOfLife();
			void Initialize();
			void LoadContent();
			void UnloadContent();
			void Update(GameTime* gameTime);
			void Draw(GameTime* gameTime);
	};
}

#endif